version: '3.8'
networks:
  backend:
    driver: overlay
secrets:
  secret_postgres:
    external: true
services:
  database:
    image: postgres:12.3
    environment:
      environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_postgres
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
