version: '3'
services:
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - pgdataknowledge:/var/lib/postgresql/data
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: docker
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodata:/data/db
volumes:
  pgdataknowledge:
  mongodata:
